name: Hello
run-name: Run by @${{ github.actor }}
on: push
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Helow, word"
      - uses: actions/checkout@v4
      - id: source
        run: echo "result=Hello" >> "${GITHUB_OUTPUT}" # GITHUB_OUTPUTへ書き出し
      - env:
          RESULT: ${{ steps.source.outputs.result }} # stepsコンテキストから参照
        run: echo "${RESULT}"
  share:
    runs-on: ubuntu-latest
    steps:
      - run: echo "RESULT=hello" >> "${GITHUB_ENV}" # GITHUB_ENVへ書き出し
      - run: echo "${RESULT}" # GITHUB_ENVから参照
